#try except 구문을 사용합니다.
try:
    #파일을 엽니다.
    file = open("info.txt", "w")
    #여러가지 처리를 수행합니다.
    #파일을 닫습니다.
    file.close()
except Exception as e: # 오류가 발생하면 실행 됨
    print(e) 

print("#파일이 제대로 닫혔는지 확인하기")
print("file.closed:", file.closed)
#실행결과: #파일이 제대로 닫혔는지 확인하기
#         #file.closed: True
#--------------------------------------------------------
#try except 구문을 사용합니다.
try:
    #파일을 엽니다.
    file = open("info.txt", "w")
    #여러가지 처리를 수행합니다.
    예외.발생해라()
    #파일을 닫습니다.
    file.close()
except Exception as e:
    print(e)

print("#파일이 제대로 닫혔는지 확인하기")
print("file.closed:",file.closed)
#실행결과: #name '예외' is not defined
#         #파일이 제대로 닫혔는지 확인하기
#         #file.closed: False

#------------finally 구문을 이용하여 닫아줘야 함----------
#try except 구문을 사용합니다.
try:
    #파일을 엽니다.
    file = open("info.txt", "w")
    #여러가지 처리를 수행합니다.
    예외.발생해라()
    #파일을 닫습니다.
    file.close()
except Exception as e:
    print(e)
finally:
    #파일을 닫습니다.
    file.close()

print("#파일이 제대로 닫혔는지 확인하기")
print("file.closed:",file.closed)
#실행결과: #name '예외' is not defined
#         #파일이 제대로 닫혔는지 확인하기
#         #file.closed: True
